### PR TITLE
Some updates on the Uritemplate branch

### PR DESCRIPTION
**Pull request by green-coder**
Just FYI ...

### CODE REVIEW

**Comment by aslakhellesoy** [comment]
Did you intend to close-open-close this??

**Comment by green-coder** [comment]
I didn't 'really' intent to close-open-close. There was a button, and there was curiosity ... and there was a strong desire to see what would happen, as this is one of my first pull request. Sorry about that, I didn't know that each action would be publicly logged.

I am referring to the Maven project that I created: https://github.com/green-coder/wo-furi

**Comment by aslakhellesoy** [comment]
Oh I see :-)

Are you planning to publish that jar in the maven repo? What will you do when/if wo-furi makes a new zip release on google code? It's usually better to use `git-svn` when mirroring a subversion project. That allows you to pull in new changes from subversion into git. You currently can't do that.

Another option could be to use jarjar to merge wo-furi into the webbit-rest jar, and not rely on a wo-furi jar available in maven at all. What do you think?

**Comment by green-coder** [comment]
I don't plan to push it to the Central Maven Repository for now. I notified the author of wo-furi about the Maven support I added, and I will wait a while to see if he will integrate it with his version and do the push to the Maven Central Repository or not.

You made a good suggestion, I might rebuild the git repo using git-svn later. If the author doesn't answer after a while, I might publish furi on the Central Maven Repository using a different groupID (com.lemoulinstudio.xxx). I don't like the jar approach as it sounds more like a hack, while there is no reason not to use the classic Maven way.

About this pull request: I realized that I will not use webbit-rest and RESTeasy for my project. I am also not sure if I will use the uritemplate branch of webbit or not.

I will use Furi for sure, as I still want to implement a RESTful web service API and this library seems useful.

**Comment by aslakhellesoy** [comment]
Thanks for the heads up. I'm going to retire https://github.com/aslakhellesoy/webbit-rest and instead create a https://github.com/webbit/webbit-rest project - based on the wo-furi stuff. Can't promise when though.

**Comment by green-coder** [comment]
too old, closing

**Pull request closed without merging**
